apiVersion: v1
kind: Template
labels:
  app: ara
  template: ara-buildconfig
metadata:
  annotations:
    description: ARA - BuildConfig
      see https://github.com/Worteks/docker-ara
    iconClass: icon-openshift
    openshift.io/display-name: Ansible Runtime Analysis
    openshift.io/provider-display-name: Worteks
    openshift.io/support-url: https://www.worteks.com
    tags: ara
  name: ara-buildconfig
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Wsweet ARA images
    labels:
      name: ara-${FRONTNAME}-${ARA_REPOSITORY_REF}
    name: ara-${FRONTNAME}-${ARA_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
    source:
      contextDir: /
      git:
        uri: ${ARA_REPOSITORY_URL}
        ref: "${ARA_REPOSITORY_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: ara-${FRONTNAME}:${ARA_REPOSITORY_REF}
    triggers:
    - type: ConfigChange
parameters:
- name: ARA_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: ARA_REPOSITORY_URL
  description: The URL of the repository with your ARA Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/Worteks/docker-ara.git
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
