apiVersion: v1
kind: Template
labels:
  app: ara
  template: ara-imagestream
metadata:
  annotations:
    description: ARA - ImageStream
      see https://github.com/Worteks/docker-ara
    iconClass: icon-openshift
    openshift.io/display-name: Ansible Runtime Analysis
    openshift.io/provider-display-name: Worteks
    openshift.io/support-url: https://www.worteks.com
    tags: ara
  name: ara-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Wsweet ARA image
    name: ara-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
